/**
 * This code was generated by Builder.io.
 */
import React, { useState } from "react";

const EmotionalAnalysis = () => {
  const [userInput, setUserInput] = useState("");
  const [mood, setMood] = useState("");

  const analyzeMood = () => {
    // This is a placeholder for NLP analysis
    // In a real application, this would call an API or use a library
    const moodMap = {
      happy: ["joy", "excited", "great"],
      sad: ["down", "depressed", "unhappy"],
      angry: ["mad", "frustrated", "annoyed"],
      anxious: ["worried", "nervous", "stressed"],
    };

    const lowercaseInput = userInput.toLowerCase();
    for (const [detectedMood, keywords] of Object.entries(moodMap)) {
      if (keywords.some((keyword) => lowercaseInput.includes(keyword))) {
        setMood(detectedMood);
        return;
      }
    }
    setMood("neutral");
  };

  return (
    <div className="bg-white p-6 rounded-lg shadow-md">
      <h2 className="text-xl font-semibold mb-4">
        Real-time Emotional Analysis
      </h2>
      <textarea
        className="w-full p-2 border rounded mb-4"
        rows="4"
        placeholder="How are you feeling today?"
        value={userInput}
        onChange={(e) => setUserInput(e.target.value)}
      ></textarea>
      <button
        className="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600"
        onClick={analyzeMood}
      >
        Analyze Mood
      </button>
      {mood && (
        <p className="mt-4">
          Based on your input, you seem to be feeling <strong>{mood}</strong>.
        </p>
      )}
    </div>
  );
};

export default EmotionalAnalysis;
