/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Footer = () => {
  return (
    <footer className="bg-gray-800 text-white p-4 mt-8">
      <div className="container mx-auto text-center">
        <p>&copy; Designed by Rahul - Mental Health Assistant </p>
        <p className="mt-2">
          <a href="#privacy" className="hover:text-blue-300 mr-4">
            Privacy Policy
          </a>
          <a href="#terms" className="hover:text-blue-300 mr-4">
            Terms of Service
          </a>
          <a href="#contact" className="hover:text-blue-300">
            Contact Us
          </a>
        </p>
      </div>
    </footer>
  );
};

export default Footer;
