/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import EmotionalAnalysis from "./EmotionalAnalysis";
import SupportPlan from "./SupportPlan";
import PeerSupport from "./PeerSupport";
import EmergencyAlert from "./EmergencyAlert";
import Footer from "./Footer";

const MentalHealthAssistant = () => {
  return (
    <div className="min-h-screen bg-gray-100">
      <Header />
      <main className="container mx-auto px-4 py-8">
        <h1 className="text-3xl font-bold mb-8 text-center">
          Personalized Mental Health Assistant
        </h1>
        <EmotionalAnalysis />
        <SupportPlan />
        <PeerSupport />
        <EmergencyAlert />
      </main>
      <Footer />
    </div>
  );
};

export default MentalHealthAssistant;
