/**
 * This code was generated by Builder.io.
 */
import React, { useState } from "react";

const PeerSupport = () => {
  const [topic, setTopic] = useState("");
  const [peers, setPeers] = useState([]);

  const findPeers = () => {
    // This is a placeholder for peer matching logic
    // In a real application, this would call an API to find and match peers
    const mockPeers = [
      { id: 1, name: "Anonymous User 1", experience: "Anxiety" },
      { id: 2, name: "Anonymous User 2", experience: "Depression" },
      { id: 3, name: "Anonymous User 3", experience: "Stress Management" },
    ];

    setPeers(
      mockPeers.filter((peer) =>
        peer.experience.toLowerCase().includes(topic.toLowerCase())
      )
    );
  };

  return (
    <div className="bg-white p-6 rounded-lg shadow-md mt-6">
      <h2 className="text-xl font-semibold mb-4">Anonymous Peer Support</h2>
      <input
        type="text"
        className="w-full p-2 border rounded mb-4"
        placeholder="Enter a topic or experience"
        value={topic}
        onChange={(e) => setTopic(e.target.value)}
      />
      <button
        className="bg-purple-500 text-white px-4 py-2 rounded hover:bg-purple-600"
        onClick={findPeers}
      >
        Find Peers
      </button>
      {peers.length > 0 && (
        <div className="mt-4">
          <h3 className="font-semibold mb-2">Matched Peers:</h3>
          <ul className="list-disc pl-5">
            {peers.map((peer) => (
              <li key={peer.id}>
                {peer.name} - Experience: {peer.experience}
              </li>
            ))}
          </ul>
        </div>
      )}
    </div>
  );
};

export default PeerSupport;
